# Generated by Django 3.0b1 on 2019-11-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksiazki', to='biblioteka.Autor'),
        ),
    ]
